backaddress: Erika Musterfrau, Musterstraße 1, 12345 Musterstadt
fromname: Erika Musterfrau
fromaddress: "Musterstraße 1  \n 12345 Musterstadt\n"
place: Musterstadt
to: "Musterfirma GmbH  \nMax Mustermann  \nMusterstraße 2  \n12345 Musterstadt\n"
date: 01.01.2023
subject: Musterbrief
signature: Erika Musterfrau
